name = "QuantumHamlet"
uuid = "6dd259e6-3040-4cc2-aafd-5578a5416026"
authors = ["Anthony Micciche <amicciche@umass.edu>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
GraphsFlows = "06909019-6f44-4949-96fc-b9d9aaa02889"
QuantumClifford = "0525e862-1e90-11e9-3e4d-1b39d7109de1"

[compat]
Colors = "0.13.0"
Graphs = "1.12.0"
GraphsFlows = "0.1.1"
