name = "QuantumHamlet"
uuid = "6dd259e6-3040-4cc2-aafd-5578a5416026"
authors = ["Anthony Micciche <amicciche@umass.edu>"]
version = "0.1.0"

[deps]
BipartiteMatching = "79040ab4-24c8-4c92-950c-d48b5991a0f6"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
GraphsFlows = "06909019-6f44-4949-96fc-b9d9aaa02889"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
MultiwayNumberPartitioning = "76062700-569f-48fc-9444-88b66f57fbe9"
QuantumClifford = "0525e862-1e90-11e9-3e4d-1b39d7109de1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
BipartiteMatching = "0.1.1"
Colors = "0.13.0"
Graphs = "1.12.0"
GraphsFlows = "0.1.1"
HiGHS = "1.15.0"
MultiwayNumberPartitioning = "0.1.1"
Random = "1.11.0"
